
export const DARK_COLORS = {
    PRIMARY_COLOR: "#FAD348",
    SECONDARY_COLOR: "#000000",
    TERTIARY_COLOR: "#D9D9D9",
    PRIMARY_TEXT_COLOR: "#040100",
    SECONDARY_TEXT_COLOR: "#000000",
    TERTIARY_TEXT_COLOR: "#D9D9D9",
    PRIMARY_BACKGROUND_COLOR: "#2B2B2B",
    SECONDARY_BACKGROUND_COLOR: "#FFFFFF"
}

export const LIGHT_COLORS = {
    PRIMARY_COLOR: "#FAD348",
    SECONDARY_COLOR: "#000000",
    TERTIARY_COLOR: "#D9D9D9",
    PRIMARY_TEXT_COLOR: "#040100",
    SECONDARY_TEXT_COLOR: "#000000",
    TERTIARY_TEXT_COLOR: "#D9D9D9",
    PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
    SECONDARY_BACKGROUND_COLOR: "#2B2B2B"
}